if not bobmods then bobmods = {} end
if not bobmods.power then bobmods.power = {} end

require("prototypes.category")

require("prototypes.burner-generator")
require("prototypes.burner-reactor")
require("prototypes.heat-pipes")

require("prototypes.entity.accumulators")
require("prototypes.entity.boilers")
require("prototypes.entity.oil-boilers")
require("prototypes.entity.poles")
require("prototypes.entity.solar-panels")
require("prototypes.entity.steam-engines")
require("prototypes.entity.heat-exchangers")
require("prototypes.entity.steam-turbines")
require("prototypes.entity.fluid-generator")
require("prototypes.entity.nuclear")

require("prototypes.item.accumulators")
require("prototypes.item.boilers")
require("prototypes.item.oil-boilers")
require("prototypes.item.poles")
require("prototypes.item.solar-panels")
require("prototypes.item.steam-engines")
require("prototypes.item.heat-exchangers")
require("prototypes.item.steam-turbines")
require("prototypes.item.fluid-generator")
require("prototypes.item.nuclear")

require("prototypes.recipe.accumulators")
require("prototypes.recipe.boilers")
require("prototypes.recipe.oil-boilers")
require("prototypes.recipe.poles")
require("prototypes.recipe.solar-panels")
require("prototypes.recipe.steam-engines")
require("prototypes.recipe.heat-exchangers")
require("prototypes.recipe.steam-turbines")
require("prototypes.recipe.fluid-generator")
require("prototypes.recipe.nuclear")

require("prototypes.technology.accumulators")
require("prototypes.technology.boilers")
require("prototypes.technology.oil-boilers")
require("prototypes.technology.poles")
require("prototypes.technology.solar-panels")
require("prototypes.technology.steam-engines")
require("prototypes.technology.heat-exchangers")
require("prototypes.technology.steam-turbines")
require("prototypes.technology.fluid-generator")
require("prototypes.technology.nuclear")

