data:extend({
  {
    type = "equipment-grid",
    name = "bob-car",
    width = 8,
    height = 2,
    equipment_categories = { "car", "vehicle" },
  },
  {
    type = "equipment-grid",
    name = "bob-tank",
    width = 6,
    height = 8,
    equipment_categories = { "tank", "vehicle", "armoured-vehicle" },
  },
  {
    type = "equipment-grid",
    name = "bob-tank-2",
    width = 6,
    height = 10,
    equipment_categories = { "tank", "vehicle", "armoured-vehicle" },
  },
  {
    type = "equipment-grid",
    name = "bob-tank-3",
    width = 6,
    height = 12,
    equipment_categories = { "tank", "vehicle", "armoured-vehicle" },
  },

  {
    type = "equipment-grid",
    name = "bob-locomotive",
    width = 8,
    height = 2,
    equipment_categories = { "train", "vehicle", "locomotive" },
  },
  {
    type = "equipment-grid",
    name = "bob-cargo-wagon",
    width = 8,
    height = 2,
    equipment_categories = { "train", "vehicle", "cargo-wagon" },
  },
  {
    type = "equipment-grid",
    name = "bob-wagon",
    width = 8,
    height = 2,
    equipment_categories = { "train", "vehicle" },
  },
  {
    type = "equipment-grid",
    name = "bob-locomotive-2",
    width = 8,
    height = 3,
    equipment_categories = { "train", "vehicle", "locomotive" },
  },
  {
    type = "equipment-grid",
    name = "bob-cargo-wagon-2",
    width = 8,
    height = 3,
    equipment_categories = { "train", "vehicle", "cargo-wagon" },
  },
  {
    type = "equipment-grid",
    name = "bob-wagon-2",
    width = 8,
    height = 3,
    equipment_categories = { "train", "vehicle" },
  },
  {
    type = "equipment-grid",
    name = "bob-locomotive-3",
    width = 8,
    height = 4,
    equipment_categories = { "train", "vehicle", "locomotive" },
  },
  {
    type = "equipment-grid",
    name = "bob-cargo-wagon-3",
    width = 8,
    height = 4,
    equipment_categories = { "train", "vehicle", "cargo-wagon" },
  },
  {
    type = "equipment-grid",
    name = "bob-wagon-3",
    width = 8,
    height = 4,
    equipment_categories = { "train", "vehicle" },
  },

  {
    type = "equipment-grid",
    name = "bob-armoured-wagon",
    width = 10,
    height = 4,
    equipment_categories = { "train", "vehicle", "armoured-vehicle", "armoured-train" },
  },
  {
    type = "equipment-grid",
    name = "bob-armoured-locomotive",
    width = 10,
    height = 6,
    equipment_categories = {
      "train",
      "vehicle",
      "locomotive",
      "armoured-vehicle",
      "armoured-train",
      "armoured-locomotive",
    },
  },
  {
    type = "equipment-grid",
    name = "bob-armoured-cargo-wagon",
    width = 10,
    height = 6,
    equipment_categories = {
      "train",
      "vehicle",
      "cargo-wagon",
      "armoured-vehicle",
      "armoured-train",
      "armoured-cargo-wagon",
    },
  },
  {
    type = "equipment-grid",
    name = "bob-armoured-wagon-2",
    width = 10,
    height = 6,
    equipment_categories = { "train", "vehicle", "armoured-vehicle", "armoured-train" },
  },
  {
    type = "equipment-grid",
    name = "bob-armoured-locomotive-2",
    width = 10,
    height = 8,
    equipment_categories = {
      "train",
      "vehicle",
      "locomotive",
      "armoured-vehicle",
      "armoured-train",
      "armoured-locomotive",
    },
  },
  {
    type = "equipment-grid",
    name = "bob-armoured-cargo-wagon-2",
    width = 10,
    height = 8,
    equipment_categories = {
      "train",
      "vehicle",
      "cargo-wagon",
      "armoured-vehicle",
      "armoured-train",
      "armoured-cargo-wagon",
    },
  },
  {
    type = "equipment-grid",
    name = "bob-armoured-wagon-3",
    width = 10,
    height = 8,
    equipment_categories = { "train", "vehicle", "armoured-vehicle", "armoured-train" },
  },

  {
    type = "equipment-grid",
    name = "unarmed-grid",
    width = 5,
    height = 10,
    equipment_categories = { "car", "unarmed-vehicle" },
  },

  {
    type = "equipment-grid",
    name = "boat-grid",
    width = 6,
    height = 12,
    equipment_categories = { "vehicle", "armoured-vehicle", "cargo-wagon" },
  },
})
