local plate_drop_move = {
  filename = "__base__/sound/item/metal-small-inventory-move.ogg",
  volume = 0.8,
}
local plate_pick = {
  filename = "__base__/sound/item/metal-small-inventory-pickup.ogg",
  volume = 0.8,
}

data:extend({
  {
    type = "item",
    name = "bob-bronze-alloy",
    icon = "__bobplates__/graphics/icons/plate/bronze-plate.png",
    icon_size = 64,
    subgroup = "bob-alloy",
    order = "c-b-a[bob-bronze]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
  {
    type = "item",
    name = "bob-brass-alloy",
    icon = "__bobplates__/graphics/icons/plate/brass-plate.png",
    icon_size = 64,
    subgroup = "bob-alloy",
    order = "c-b-b[bob-brass]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
  {
    type = "item",
    name = "bob-copper-tungsten-alloy",
    icon = "__bobplates__/graphics/icons/plate/copper-tungsten-plate.png",
    icon_size = 32,
    subgroup = "bob-alloy",
    order = "c-b-d[bob-copper-tungsten]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
  {
    type = "item",
    name = "bob-tungsten-carbide",
    icon = "__bobplates__/graphics/icons/plate/tungsten-carbide-plate.png",
    icon_size = 64,
    subgroup = "bob-alloy",
    order = "c-b-d[bob-tungsten-carbide]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
  {
    type = "item",
    name = "bob-gunmetal-alloy",
    icon = "__bobplates__/graphics/icons/plate/gunmetal-plate.png",
    icon_size = 64,
    subgroup = "bob-alloy",
    order = "c-b-e[bob-gunmetal]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },

  {
    type = "item",
    name = "bob-invar-alloy",
    icon = "__bobplates__/graphics/icons/plate/invar-plate.png",
    icon_size = 64,
    subgroup = "bob-alloy",
    order = "c-b-f[bob-invar]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
  {
    type = "item",
    name = "bob-nitinol-alloy",
    icon = "__bobplates__/graphics/icons/plate/nitinol-plate.png",
    icon_size = 32,
    subgroup = "bob-alloy",
    order = "c-b-g[bob-nitinol]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
  {
    type = "item",
    name = "bob-cobalt-steel-alloy",
    icon = "__bobplates__/graphics/icons/plate/cobalt-steel-plate.png",
    icon_size = 32,
    subgroup = "bob-alloy",
    order = "c-b-i[bob-cobalt-steel]",
    stack_size = 200,
    drop_sound = plate_drop_move,
    inventory_move_sound = plate_drop_move,
    pick_sound = plate_pick,
  },
})
