data:extend({
  {
    type = "item",
    name = "electrolyser",
    icon = "__bobplates__/graphics/icons/electrolyser.png",
    icon_size = 32,
    subgroup = "production-machine",
    order = "e[electrolyser-1]",
    place_result = "electrolyser",
    stack_size = 50,
  },

  {
    type = "item",
    name = "stone-mixing-furnace",
    icon = "__bobplates__/graphics/icons/stone-mixing-furnace.png",
    icon_size = 32,
    subgroup = "bob-smelting-machine",
    order = "b[mixing-furnace-1]",
    place_result = "stone-mixing-furnace",
    stack_size = 50,
  },
  {
    type = "item",
    name = "steel-mixing-furnace",
    icon = "__base__/graphics/icons/steel-furnace.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "bob-smelting-machine",
    order = "b[mixing-furnace-2]",
    place_result = "steel-mixing-furnace",
    stack_size = 50,
  },
  {
    type = "item",
    name = "electric-mixing-furnace",
    icon = "__bobplates__/graphics/icons/electric-mixing-furnace.png",
    icon_size = 32,
    subgroup = "bob-smelting-machine",
    order = "c[electric-mixing-furnace]",
    place_result = "electric-mixing-furnace",
    stack_size = 50,
  },

  {
    type = "item",
    name = "stone-chemical-furnace",
    icon = "__bobplates__/graphics/icons/stone-chemical-furnace.png",
    icon_size = 32,
    subgroup = "bob-smelting-machine",
    order = "b[chemical-boiler-1]",
    place_result = "stone-chemical-furnace",
    stack_size = 50,
  },
  {
    type = "item",
    name = "steel-chemical-furnace",
    icon = "__base__/graphics/icons/steel-furnace.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "bob-smelting-machine",
    order = "b[chemical-boiler-2]",
    place_result = "steel-chemical-furnace",
    stack_size = 50,
  },
  {
    type = "item",
    name = "electric-chemical-furnace",
    icon = "__bobplates__/graphics/icons/chemical-furnace.png",
    icon_size = 32,
    subgroup = "bob-smelting-machine",
    order = "c[chemical-furnace]",
    place_result = "electric-chemical-furnace",
    stack_size = 50,
  },

  {
    type = "item",
    name = "air-pump",
    icon = "__bobplates__/graphics/icons/air-pump-1.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[air-pump-1]",
    place_result = "air-pump",
    stack_size = 50,
  },

  {
    type = "item",
    name = "air-pump-2",
    icon = "__bobplates__/graphics/icons/air-pump-2.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[air-pump-2]",
    place_result = "air-pump-2",
    stack_size = 50,
  },

  {
    type = "item",
    name = "air-pump-3",
    icon = "__bobplates__/graphics/icons/air-pump-3.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[air-pump-3]",
    place_result = "air-pump-3",
    stack_size = 50,
  },

  {
    type = "item",
    name = "air-pump-4",
    icon = "__bobplates__/graphics/icons/air-pump-4.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[air-pump-4]",
    place_result = "air-pump-4",
    stack_size = 50,
  },

  {
    type = "item",
    name = "water-pump",
    icon = "__bobplates__/graphics/icons/water-pump-1.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[water-pump-1]",
    place_result = "water-pump",
    stack_size = 50,
  },

  {
    type = "item",
    name = "water-pump-2",
    icon = "__bobplates__/graphics/icons/water-pump-2.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[water-pump-2]",
    place_result = "water-pump-2",
    stack_size = 50,
  },

  {
    type = "item",
    name = "water-pump-3",
    icon = "__bobplates__/graphics/icons/water-pump-3.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[water-pump-3]",
    place_result = "water-pump-3",
    stack_size = 50,
  },

  {
    type = "item",
    name = "water-pump-4",
    icon = "__bobplates__/graphics/icons/water-pump-4.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "e[water-pump-4]",
    place_result = "water-pump-4",
    stack_size = 50,
  },

  {
    type = "item",
    name = "bob-small-inline-storage-tank",
    icon = "__bobplates__/graphics/icons/small-storage-tank.png",
    icon_size = 32,
    subgroup = "bob-storage",
    order = "b[fluid]-a[storage-tank-0a]",
    place_result = "bob-small-inline-storage-tank",
    stack_size = 50,
  },

  {
    type = "item",
    name = "bob-small-storage-tank",
    icon = "__bobplates__/graphics/icons/small-storage-tank.png",
    icon_size = 32,
    subgroup = "bob-storage",
    order = "b[fluid]-a[storage-tank-0b]",
    place_result = "bob-small-storage-tank",
    stack_size = 50,
  },

  {
    type = "item",
    name = "void-pump",
    icon = "__bobplates__/graphics/icons/void-pump.png",
    icon_size = 32,
    subgroup = "bob-pump",
    order = "void-pump",
    place_result = "void-pump",
    stack_size = 50,
  },
})
