local gem_drop_move = {
  filename = "__base__/sound/item/resource-inventory-move.ogg",
  volume = 0.8,
}
local gem_pick = {
  filename = "__base__/sound/item/resource-inventory-pickup.ogg",
  volume = 0.6,
}

data:extend({
  {
    type = "item",
    name = "bob-ruby-3",
    icon = "__bobplates__/graphics/icons/gems/ruby-3.png",
    icon_size = 32,
    subgroup = "bob-gems-raw",
    order = "a-3",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-sapphire-3",
    icon = "__bobplates__/graphics/icons/gems/sapphire-3.png",
    icon_size = 32,
    subgroup = "bob-gems-raw",
    order = "b-3",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-emerald-3",
    icon = "__bobplates__/graphics/icons/gems/emerald-3.png",
    icon_size = 32,
    subgroup = "bob-gems-raw",
    order = "c-3",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-amethyst-3",
    icon = "__bobplates__/graphics/icons/gems/amethyst-3.png",
    icon_size = 32,
    subgroup = "bob-gems-raw",
    order = "d-3",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-topaz-3",
    icon = "__bobplates__/graphics/icons/gems/topaz-3.png",
    icon_size = 32,
    subgroup = "bob-gems-raw",
    order = "e-3",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-diamond-3",
    icon = "__bobplates__/graphics/icons/gems/diamond-3.png",
    icon_size = 32,
    subgroup = "bob-gems-raw",
    order = "f-3",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },

  {
    type = "item",
    name = "bob-ruby-4",
    icon = "__bobplates__/graphics/icons/gems/ruby-4.png",
    icon_size = 32,
    subgroup = "bob-gems-cut",
    order = "a-4",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-sapphire-4",
    icon = "__bobplates__/graphics/icons/gems/sapphire-4.png",
    icon_size = 32,
    subgroup = "bob-gems-cut",
    order = "b-4",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-emerald-4",
    icon = "__bobplates__/graphics/icons/gems/emerald-4.png",
    icon_size = 32,
    subgroup = "bob-gems-cut",
    order = "c-4",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-amethyst-4",
    icon = "__bobplates__/graphics/icons/gems/amethyst-4.png",
    icon_size = 32,
    subgroup = "bob-gems-cut",
    order = "d-4",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-topaz-4",
    icon = "__bobplates__/graphics/icons/gems/topaz-4.png",
    icon_size = 32,
    subgroup = "bob-gems-cut",
    order = "e-4",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-diamond-4",
    icon = "__bobplates__/graphics/icons/gems/diamond-4.png",
    icon_size = 32,
    subgroup = "bob-gems-cut",
    order = "f-4",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },

  {
    type = "item",
    name = "bob-ruby-5",
    icon = "__bobplates__/graphics/icons/gems/ruby-5.png",
    icon_size = 32,
    subgroup = "bob-gems-polished",
    order = "a-5",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-sapphire-5",
    icon = "__bobplates__/graphics/icons/gems/sapphire-5.png",
    icon_size = 32,
    subgroup = "bob-gems-polished",
    order = "b-5",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-emerald-5",
    icon = "__bobplates__/graphics/icons/gems/emerald-5.png",
    icon_size = 32,
    subgroup = "bob-gems-polished",
    order = "c-5",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-amethyst-5",
    icon = "__bobplates__/graphics/icons/gems/amethyst-5.png",
    icon_size = 32,
    subgroup = "bob-gems-polished",
    order = "d-5",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-topaz-5",
    icon = "__bobplates__/graphics/icons/gems/topaz-5.png",
    icon_size = 32,
    subgroup = "bob-gems-polished",
    order = "e-5",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
  {
    type = "item",
    name = "bob-diamond-5",
    icon = "__bobplates__/graphics/icons/gems/diamond-5.png",
    icon_size = 32,
    subgroup = "bob-gems-polished",
    order = "f-5",
    stack_size = 100,
    drop_sound = gem_drop_move,
    inventory_move_sound = gem_drop_move,
    pick_sound = gem_pick,
  },
})
