data:extend({
  {
    type = "item",
    name = "tin-plate",
    icon = "__bobplates__/graphics/icons/plate/tin-plate.png",
    icon_size = 32,
    subgroup = "bob-material",
    order = "c-a-a[tin-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "silver-plate",
    icon = "__bobplates__/graphics/icons/plate/silver-plate.png",
    icon_size = 32,
    subgroup = "bob-material",
    order = "c-a-c[silver-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-lead-plate",
    icon = "__bobplates__/graphics/icons/plate/lead-plate.png",
    icon_size = 64,
    subgroup = "bob-material",
    order = "c-a-f[bob-lead-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-gold-plate",
    icon = "__bobplates__/graphics/icons/plate/gold-plate.png",
    icon_size = 64,
    subgroup = "bob-material",
    order = "c-a-d[bob-gold-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-nickel-plate",
    icon = "__bobplates__/graphics/icons/plate/nickel-plate.png",
    icon_size = 64,
    subgroup = "bob-material",
    order = "c-a-f[bob-nickel-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-zinc-plate",
    icon = "__bobplates__/graphics/icons/plate/zinc-plate.png",
    icon_size = 32,
    subgroup = "bob-material",
    order = "c-a-b[bob-zinc-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-aluminium-plate",
    icon = "__bobplates__/graphics/icons/plate/aluminium-plate.png",
    icon_size = 64,
    subgroup = "bob-material",
    order = "c-a-g[bob-aluminium-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-titanium-plate",
    icon = "__bobplates__/graphics/icons/plate/titanium-plate.png",
    icon_size = 32,
    subgroup = "bob-material",
    order = "c-a-h[bob-titanium-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-tungsten-plate",
    icon = "__bobplates__/graphics/icons/plate/tungsten-plate.png",
    icon_size = 32,
    subgroup = "bob-material",
    order = "c-a-i[bob-tungsten-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "bob-silicon-plate",
    icon = "__bobplates__/graphics/icons/plate/silicon-plate.png",
    icon_size = 32,
    subgroup = "bob-material",
    order = "c-a-e[bob-silicon-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "lithium",
    icon = "__bobplates__/graphics/icons/plate/lithium-plate.png",
    icon_size = 64,
    subgroup = "bob-material",
    order = "c-a-e[lithium-plate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "cobalt-plate",
    icon = "__bobplates__/graphics/icons/plate/cobalt-plate.png",
    icon_size = 64,
    subgroup = "bob-material",
    order = "c-a-j[cobalt-plate]",
    stack_size = 200,
  },
})
