local electronic_board_drop_move = {
  filename = "__base__/sound/item/electric-small-inventory-move.ogg",
  volume = 1,
}
local electronic_board_pick = {
  filename = "__base__/sound/item/electric-small-inventory-pickup.ogg",
  volume = 0.7,
}

data:extend({
  {
    type = "item",
    name = "bob-module-case",
    icon = "__bobmodules__/graphics/icons/module-case.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-0[bob-module-case]",
    stack_size = 100,
    drop_sound = {
      filename = "__base__/sound/item/metal-small-inventory-move.ogg",
      volume = 0.8,
    },
    inventory_move_sound = {
      filename = "__base__/sound/item/metal-small-inventory-move.ogg",
      volume = 0.8,
    },
    pick_sound = {
      filename = "__base__/sound/item/metal-small-inventory-pickup.ogg",
      volume = 0.8,
    },
  },
  {
    type = "item",
    name = "bob-module-circuit-board",
    icon = "__bobmodules__/graphics/icons/module-circuit-board.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-b4[bob-module-circuit-board]",
    stack_size = 200,
    drop_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.7,
      speed = 0.85,
    },
    inventory_move_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.7,
      speed = 0.85,
    },
    pick_sound = {
      filename = "__base__/sound/item/wood-inventory-pickup.ogg",
      volume = 0.8,
      speed = 0.85,
    },
  },
  {
    type = "item",
    name = "bob-speed-processor",
    icon = "__bobmodules__/graphics/icons/speed-processor.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c4[bob-speed-processor-1]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-efficiency-processor",
    icon = "__bobmodules__/graphics/icons/efficiency-processor.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c5[bob-efficiency-processor-1]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-productivity-processor",
    icon = "__bobmodules__/graphics/icons/productivity-processor.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c6[bob-productivity-processor-1]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-pollution-clean-processor",
    icon = "__bobmodules__/graphics/icons/pollution-clean-processor.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c7[bob-pollution-clean-processor-1]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-pollution-create-processor",
    icon = "__bobmodules__/graphics/icons/pollution-create-processor.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c8[bob-pollution-create-processor-1]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
})

data:extend({
  {
    type = "item",
    name = "bob-module-contact",
    icon = "__bobmodules__/graphics/icons/module-contact.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-1[bob-module-contact]",
    stack_size = 200,
    drop_sound = {
      filename = "__base__/sound/item/metal-small-inventory-move.ogg",
      volume = 0.8,
    },
    inventory_move_sound = {
      filename = "__base__/sound/item/metal-small-inventory-move.ogg",
      volume = 0.8,
    },
    pick_sound = {
      filename = "__base__/sound/item/metal-small-inventory-pickup.ogg",
      volume = 0.8,
    },
  },
  {
    type = "item",
    name = "bob-module-processor-board",
    icon = "__bobmodules__/graphics/icons/module-processor-board.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-b5[bob-module-processor-board-1]",
    stack_size = 200,
    drop_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.7,
      speed = 0.85,
    },
    inventory_move_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.7,
      speed = 0.85,
    },
    pick_sound = {
      filename = "__base__/sound/item/wood-inventory-pickup.ogg",
      volume = 0.8,
      speed = 0.85,
    },
  },
  {
    type = "item",
    name = "bob-module-processor-board-2",
    icon = "__bobmodules__/graphics/icons/module-processor-board-2.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-b6[bob-module-processor-board-2]",
    stack_size = 200,
    drop_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.85,
      speed = 1.6,
    },
    inventory_move_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.85,
      speed = 1.6,
    },
    pick_sound = {
      filename = "__base__/sound/item/wood-inventory-pickup.ogg",
      volume = 0.85,
      speed = 1.6,
    },
  },
  {
    type = "item",
    name = "bob-module-processor-board-3",
    icon = "__bobmodules__/graphics/icons/module-processor-board-3.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-b7[bob-module-processor-board-3]",
    stack_size = 200,
    drop_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.85,
      speed = 1.6,
    },
    inventory_move_sound = {
      filename = "__base__/sound/item/wood-inventory-move.ogg",
      volume = 0.85,
      speed = 1.6,
    },
    pick_sound = {
      filename = "__base__/sound/item/wood-inventory-pickup.ogg",
      volume = 0.85,
      speed = 1.6,
    },
  },
  {
    type = "item",
    name = "bob-speed-processor-2",
    icon = "__bobmodules__/graphics/icons/speed-processor-2.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c4[bob-speed-processor-2]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-speed-processor-3",
    icon = "__bobmodules__/graphics/icons/speed-processor-3.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c4[bob-speed-processor-3]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-efficiency-processor-2",
    icon = "__bobmodules__/graphics/icons/efficiency-processor-2.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c5[bob-efficiency-processor-2]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-efficiency-processor-3",
    icon = "__bobmodules__/graphics/icons/efficiency-processor-3.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c5[bob-efficiency-processor-3]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-productivity-processor-2",
    icon = "__bobmodules__/graphics/icons/productivity-processor-2.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c6[bob-productivity-processor-2]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-productivity-processor-3",
    icon = "__bobmodules__/graphics/icons/productivity-processor-3.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c6[bob-productivity-processor-3]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-pollution-clean-processor-2",
    icon = "__bobmodules__/graphics/icons/pollution-clean-processor-2.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c7[bob-pollution-clean-processor-2]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-pollution-clean-processor-3",
    icon = "__bobmodules__/graphics/icons/pollution-clean-processor-3.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c7[bob-pollution-clean-processor-3]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-pollution-create-processor-2",
    icon = "__bobmodules__/graphics/icons/pollution-create-processor-2.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c8[bob-pollution-create-processor-2]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
  {
    type = "item",
    name = "bob-pollution-create-processor-3",
    icon = "__bobmodules__/graphics/icons/pollution-create-processor-3.png",
    icon_size = 32,
    subgroup = "module-intermediates",
    order = "c-c8[bob-pollution-create-processor-3]",
    stack_size = 100,
    drop_sound = electronic_board_drop_move,
    inventory_move_sound = electronic_board_drop_move,
    pick_sound = electronic_board_pick,
  },
})

if mods["quality"] then
  data:extend({
    {
      type = "item",
      name = "bob-quality-processor",
      icon = "__bobmodules__/graphics/icons/quality-processor.png",
      icon_size = 32,
      subgroup = "module-intermediates",
      order = "c-c9[bob-quality-processor-1]",
      stack_size = 100,
      drop_sound = electronic_board_drop_move,
      inventory_move_sound = electronic_board_drop_move,
      pick_sound = electronic_board_pick,
    },
    {
      type = "item",
      name = "bob-quality-processor-2",
      icon = "__bobmodules__/graphics/icons/quality-processor-2.png",
      icon_size = 32,
      subgroup = "module-intermediates",
      order = "c-c9[bob-quality-processor-2]",
      stack_size = 100,
      drop_sound = electronic_board_drop_move,
      inventory_move_sound = electronic_board_drop_move,
      pick_sound = electronic_board_pick,
    },
    {
      type = "item",
      name = "bob-quality-processor-3",
      icon = "__bobmodules__/graphics/icons/quality-processor-3.png",
      icon_size = 32,
      subgroup = "module-intermediates",
      order = "c-c9[bob-quality-processor-3]",
      stack_size = 100,
      drop_sound = electronic_board_drop_move,
      inventory_move_sound = electronic_board_drop_move,
      pick_sound = electronic_board_pick,
    },
  })
end
