data.raw["mining-drill"]["pumpjack"].fast_replaceable_group = "pumpjack"
data.raw.item["pumpjack"].order = "b[fluids]-b[pumpjack-1]"

if settings.startup["bobmods-mining-pumpjacks"].value == true then
  data:extend({
    {
      type = "item",
      name = "bob-pumpjack-1",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "extraction-machine",
      order = "b[fluids]-b[pumpjack-2]",
      place_result = "bob-pumpjack-1",
      stack_size = 20,
    },
    {
      type = "item",
      name = "bob-pumpjack-2",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "extraction-machine",
      order = "b[fluids]-b[pumpjack-3]",
      place_result = "bob-pumpjack-2",
      stack_size = 20,
    },
    {
      type = "item",
      name = "bob-pumpjack-3",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "extraction-machine",
      order = "b[fluids]-b[pumpjack-4]",
      place_result = "bob-pumpjack-3",
      stack_size = 20,
    },
    {
      type = "item",
      name = "bob-pumpjack-4",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "extraction-machine",
      order = "b[fluids]-b[pumpjack-5]",
      place_result = "bob-pumpjack-4",
      stack_size = 20,
    },
  })

  data:extend({
    {
      type = "recipe",
      name = "bob-pumpjack-1",
      energy_required = 5,
      ingredients = {
        { "pumpjack", 1 },
        { "steel-plate", 20 },
        { "iron-gear-wheel", 10 },
        { "electronic-circuit", 5 },
        { "pipe", 10 },
      },
      results = { { type = "item", name = "bob-pumpjack-1", amount = 1 } },
      enabled = false,
    },
    {
      type = "recipe",
      name = "bob-pumpjack-2",
      energy_required = 5,
      ingredients = {
        { "bob-pumpjack-1", 1 },
        { "steel-plate", 20 },
        { "iron-gear-wheel", 10 },
        { "advanced-circuit", 5 },
        { "pipe", 10 },
      },
      results = { { type = "item", name = "bob-pumpjack-2", amount = 1 } },
      enabled = false,
    },
    {
      type = "recipe",
      name = "bob-pumpjack-3",
      energy_required = 5,
      ingredients = {
        { "bob-pumpjack-2", 1 },
        { "steel-plate", 20 },
        { "iron-gear-wheel", 10 },
        { "processing-unit", 5 },
        { "pipe", 10 },
      },
      results = { { type = "item", name = "bob-pumpjack-3", amount = 1 } },
      enabled = false,
    },
    {
      type = "recipe",
      name = "bob-pumpjack-4",
      energy_required = 5,
      ingredients = {
        { "bob-pumpjack-3", 1 },
        { "steel-plate", 20 },
        { "iron-gear-wheel", 10 },
        { "processing-unit", 5 },
        { "pipe", 10 },
      },
      results = { { type = "item", name = "bob-pumpjack-4", amount = 1 } },
      enabled = false,
    },
  })

  data:extend({
    {
      type = "mining-drill",
      name = "bob-pumpjack-1",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      flags = { "placeable-neutral", "player-creation" },
      minable = { mining_time = 1, result = "bob-pumpjack-1" },
      resource_categories = { "basic-fluid" },
      max_health = 150,
      corpse = "big-remnants",
      dying_explosion = "medium-explosion",
      collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
      selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
      drawing_box = { { -1.6, -2.5 }, { 1.5, 1.6 } },
      energy_source = {
        type = "electric",
        emissions_per_minute = 10,
        usage_priority = "secondary-input",
      },
      output_fluid_box = {
        base_area = 2,
        base_level = 1,
        pipe_covers = pipecoverspictures(),
        pipe_connections = {
          {
            type = "output",
            positions = { { 1, -2 }, { 2, -1 }, { -1, 2 }, { -2, 1 } },
          },
        },
      },
      energy_usage = "171kW",
      mining_speed = 2,
      resource_searching_radius = 0.49,
      vector_to_place_result = { 0, 0 },
      module_specification = {
        module_slots = 3,
        module_info_icon_shift = { 0, 0.5 },
        module_info_multi_row_initial_height_modifier = -0.3,
      },
      fast_replaceable_group = "pumpjack",
      radius_visualisation_picture = {
        filename = "__base__/graphics/entity/pumpjack/pumpjack-radius-visualization.png",
        width = 12,
        height = 12,
      },
      monitor_visualization_tint = { r = 78, g = 173, b = 255 },
      base_picture = {
        sheets = {
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base.png",
            priority = "extra-high",
            width = 131,
            height = 137,
            shift = util.by_pixel(-2.5, -4.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base.png",
              priority = "extra-high",
              width = 261,
              height = 273,
              shift = util.by_pixel(-2.25, -4.75),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base-shadow.png",
            priority = "extra-high",
            width = 110,
            height = 111,
            draw_as_shadow = true,
            shift = util.by_pixel(6, 0.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base-shadow.png",
              width = 220,
              height = 220,
              scale = 0.5,
              draw_as_shadow = true,
              shift = util.by_pixel(6, 0.5),
            },
          },
        },
      },
      animations = {
        north = {
          layers = {
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead.png",
              line_length = 8,
              width = 104,
              height = 102,
              frame_count = 40,
              shift = util.by_pixel(-4, -24),
              animation_speed = 0.5,
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead.png",
                animation_speed = 0.5,
                scale = 0.5,
                line_length = 8,
                width = 206,
                height = 202,
                frame_count = 40,
                shift = util.by_pixel(-4, -24),
              },
            },
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead-shadow.png",
              animation_speed = 0.5,
              draw_as_shadow = true,
              line_length = 8,
              width = 155,
              height = 41,
              frame_count = 40,
              shift = util.by_pixel(17.5, 14.5),
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead-shadow.png",
                animation_speed = 0.5,
                draw_as_shadow = true,
                line_length = 8,
                width = 309,
                height = 82,
                frame_count = 40,
                scale = 0.5,
                shift = util.by_pixel(17.75, 14.5),
              },
            },
          },
        },
      },
      vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
      working_sound = {
        sound = { filename = "__base__/sound/pumpjack.ogg" },
        apparent_volume = 1.5,
      },
      circuit_wire_connection_points = circuit_connector_definitions["pumpjack"].points,
      circuit_connector_sprites = circuit_connector_definitions["pumpjack"].sprites,
      circuit_wire_max_distance = 10,
    },
    {
      type = "mining-drill",
      name = "bob-pumpjack-2",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      flags = { "placeable-neutral", "player-creation" },
      minable = { mining_time = 1, result = "bob-pumpjack-2" },
      resource_categories = { "basic-fluid" },
      max_health = 200,
      corpse = "big-remnants",
      dying_explosion = "medium-explosion",
      collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
      selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
      drawing_box = { { -1.6, -2.5 }, { 1.5, 1.6 } },
      energy_source = {
        type = "electric",
        emissions_per_minute = 10,
        usage_priority = "secondary-input",
      },
      output_fluid_box = {
        base_area = 2,
        base_level = 1,
        pipe_covers = pipecoverspictures(),
        pipe_connections = {
          {
            type = "output",
            positions = { { 1, -2 }, { 2, -1 }, { -1, 2 }, { -2, 1 } },
          },
        },
      },
      energy_usage = "243kW",
      mining_speed = 3,
      resource_searching_radius = 0.49,
      vector_to_place_result = { 0, 0 },
      module_specification = {
        module_slots = 4,
        module_info_icon_shift = { 0, 0.5 },
        module_info_multi_row_initial_height_modifier = -0.3,
      },
      fast_replaceable_group = "pumpjack",
      radius_visualisation_picture = {
        filename = "__base__/graphics/entity/pumpjack/pumpjack-radius-visualization.png",
        width = 12,
        height = 12,
      },
      monitor_visualization_tint = { r = 78, g = 173, b = 255 },
      base_picture = {
        sheets = {
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base.png",
            priority = "extra-high",
            width = 131,
            height = 137,
            shift = util.by_pixel(-2.5, -4.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base.png",
              priority = "extra-high",
              width = 261,
              height = 273,
              shift = util.by_pixel(-2.25, -4.75),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base-shadow.png",
            priority = "extra-high",
            width = 110,
            height = 111,
            draw_as_shadow = true,
            shift = util.by_pixel(6, 0.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base-shadow.png",
              width = 220,
              height = 220,
              scale = 0.5,
              draw_as_shadow = true,
              shift = util.by_pixel(6, 0.5),
            },
          },
        },
      },
      animations = {
        north = {
          layers = {
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead.png",
              line_length = 8,
              width = 104,
              height = 102,
              frame_count = 40,
              shift = util.by_pixel(-4, -24),
              animation_speed = 0.5,
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead.png",
                animation_speed = 0.5,
                scale = 0.5,
                line_length = 8,
                width = 206,
                height = 202,
                frame_count = 40,
                shift = util.by_pixel(-4, -24),
              },
            },
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead-shadow.png",
              animation_speed = 0.5,
              draw_as_shadow = true,
              line_length = 8,
              width = 155,
              height = 41,
              frame_count = 40,
              shift = util.by_pixel(17.5, 14.5),
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead-shadow.png",
                animation_speed = 0.5,
                draw_as_shadow = true,
                line_length = 8,
                width = 309,
                height = 82,
                frame_count = 40,
                scale = 0.5,
                shift = util.by_pixel(17.75, 14.5),
              },
            },
          },
        },
      },
      vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
      working_sound = {
        sound = { filename = "__base__/sound/pumpjack.ogg" },
        apparent_volume = 1.5,
      },
      circuit_wire_connection_points = circuit_connector_definitions["pumpjack"].points,
      circuit_connector_sprites = circuit_connector_definitions["pumpjack"].sprites,
      circuit_wire_max_distance = 12.5,
    },
    {
      type = "mining-drill",
      name = "bob-pumpjack-3",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      flags = { "placeable-neutral", "player-creation" },
      minable = { mining_time = 1, result = "bob-pumpjack-3" },
      resource_categories = { "basic-fluid" },
      max_health = 250,
      corpse = "big-remnants",
      dying_explosion = "medium-explosion",
      collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
      selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
      drawing_box = { { -1.6, -2.5 }, { 1.5, 1.6 } },
      energy_source = {
        type = "electric",
        emissions_per_minute = 10,
        usage_priority = "secondary-input",
      },
      output_fluid_box = {
        base_area = 2.5,
        base_level = 1,
        pipe_covers = pipecoverspictures(),
        pipe_connections = {
          {
            type = "output",
            positions = { { 1, -2 }, { 2, -1 }, { -1, 2 }, { -2, 1 } },
          },
        },
      },
      energy_usage = "306kW",
      mining_speed = 4,
      resource_searching_radius = 0.49,
      vector_to_place_result = { 0, 0 },
      module_specification = {
        module_slots = 5,
        module_info_icon_shift = { 0, 0.5 },
        module_info_multi_row_initial_height_modifier = -0.3,
      },
      fast_replaceable_group = "pumpjack",
      radius_visualisation_picture = {
        filename = "__base__/graphics/entity/pumpjack/pumpjack-radius-visualization.png",
        width = 12,
        height = 12,
      },
      monitor_visualization_tint = { r = 78, g = 173, b = 255 },
      base_picture = {
        sheets = {
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base.png",
            priority = "extra-high",
            width = 131,
            height = 137,
            shift = util.by_pixel(-2.5, -4.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base.png",
              priority = "extra-high",
              width = 261,
              height = 273,
              shift = util.by_pixel(-2.25, -4.75),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base-shadow.png",
            priority = "extra-high",
            width = 110,
            height = 111,
            draw_as_shadow = true,
            shift = util.by_pixel(6, 0.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base-shadow.png",
              width = 220,
              height = 220,
              scale = 0.5,
              draw_as_shadow = true,
              shift = util.by_pixel(6, 0.5),
            },
          },
        },
      },
      animations = {
        north = {
          layers = {
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead.png",
              line_length = 8,
              width = 104,
              height = 102,
              frame_count = 40,
              shift = util.by_pixel(-4, -24),
              animation_speed = 0.5,
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead.png",
                animation_speed = 0.5,
                scale = 0.5,
                line_length = 8,
                width = 206,
                height = 202,
                frame_count = 40,
                shift = util.by_pixel(-4, -24),
              },
            },
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead-shadow.png",
              animation_speed = 0.5,
              draw_as_shadow = true,
              line_length = 8,
              width = 155,
              height = 41,
              frame_count = 40,
              shift = util.by_pixel(17.5, 14.5),
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead-shadow.png",
                animation_speed = 0.5,
                draw_as_shadow = true,
                line_length = 8,
                width = 309,
                height = 82,
                frame_count = 40,
                scale = 0.5,
                shift = util.by_pixel(17.75, 14.5),
              },
            },
          },
        },
      },
      vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
      working_sound = {
        sound = { filename = "__base__/sound/pumpjack.ogg" },
        apparent_volume = 1.5,
      },
      circuit_wire_connection_points = circuit_connector_definitions["pumpjack"].points,
      circuit_connector_sprites = circuit_connector_definitions["pumpjack"].sprites,
      circuit_wire_max_distance = 15,
    },
    {
      type = "mining-drill",
      name = "bob-pumpjack-4",
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 64,
      icon_mipmaps = 4,
      flags = { "placeable-neutral", "player-creation" },
      minable = { mining_time = 1, result = "bob-pumpjack-4" },
      resource_categories = { "basic-fluid" },
      max_health = 300,
      corpse = "big-remnants",
      dying_explosion = "medium-explosion",
      collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
      selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
      drawing_box = { { -1.6, -2.5 }, { 1.5, 1.6 } },
      energy_source = {
        type = "electric",
        emissions_per_minute = 10,
        usage_priority = "secondary-input",
      },
      output_fluid_box = {
        base_area = 3,
        base_level = 1,
        pipe_covers = pipecoverspictures(),
        pipe_connections = {
          {
            type = "output",
            positions = { { 1, -2 }, { 2, -1 }, { -1, 2 }, { -2, 1 } },
          },
        },
      },
      energy_usage = "360kW",
      mining_speed = 5,
      resource_searching_radius = 0.49,
      vector_to_place_result = { 0, 0 },
      module_specification = {
        module_slots = 6,
        module_info_icon_shift = { 0, 0.5 },
        module_info_multi_row_initial_height_modifier = -0.3,
      },
      fast_replaceable_group = "pumpjack",
      radius_visualisation_picture = {
        filename = "__base__/graphics/entity/pumpjack/pumpjack-radius-visualization.png",
        width = 12,
        height = 12,
      },
      monitor_visualization_tint = { r = 78, g = 173, b = 255 },
      base_picture = {
        sheets = {
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base.png",
            priority = "extra-high",
            width = 131,
            height = 137,
            shift = util.by_pixel(-2.5, -4.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base.png",
              priority = "extra-high",
              width = 261,
              height = 273,
              shift = util.by_pixel(-2.25, -4.75),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/pumpjack/pumpjack-base-shadow.png",
            priority = "extra-high",
            width = 110,
            height = 111,
            draw_as_shadow = true,
            shift = util.by_pixel(6, 0.5),
            hr_version = {
              filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-base-shadow.png",
              width = 220,
              height = 220,
              scale = 0.5,
              draw_as_shadow = true,
              shift = util.by_pixel(6, 0.5),
            },
          },
        },
      },
      animations = {
        north = {
          layers = {
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead.png",
              line_length = 8,
              width = 104,
              height = 102,
              frame_count = 40,
              shift = util.by_pixel(-4, -24),
              animation_speed = 0.5,
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead.png",
                animation_speed = 0.5,
                scale = 0.5,
                line_length = 8,
                width = 206,
                height = 202,
                frame_count = 40,
                shift = util.by_pixel(-4, -24),
              },
            },
            {
              priority = "extra-high",
              filename = "__base__/graphics/entity/pumpjack/pumpjack-horsehead-shadow.png",
              animation_speed = 0.5,
              draw_as_shadow = true,
              line_length = 8,
              width = 155,
              height = 41,
              frame_count = 40,
              shift = util.by_pixel(17.5, 14.5),
              hr_version = {
                priority = "extra-high",
                filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead-shadow.png",
                animation_speed = 0.5,
                draw_as_shadow = true,
                line_length = 8,
                width = 309,
                height = 82,
                frame_count = 40,
                scale = 0.5,
                shift = util.by_pixel(17.75, 14.5),
              },
            },
          },
        },
      },
      vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
      working_sound = {
        sound = { filename = "__base__/sound/pumpjack.ogg" },
        apparent_volume = 1.5,
      },
      circuit_wire_connection_points = circuit_connector_definitions["pumpjack"].points,
      circuit_connector_sprites = circuit_connector_definitions["pumpjack"].sprites,
      circuit_wire_max_distance = 17.5,
    },
  })

  data:extend({
    {
      type = "technology",
      name = "bob-pumpjacks-1",
      icon = "__base__/graphics/technology/oil-gathering.png",
      icon_size = 256,
      icon_mipmaps = 4,
      order = "d-a-c-1",
      prerequisites = {
        "oil-processing",
      },
      unit = {
        count = 50,
        time = 30,
        ingredients = {
          { "automation-science-pack", 1 },
          { "logistic-science-pack", 1 },
        },
      },
      effects = {
        {
          type = "unlock-recipe",
          recipe = "bob-pumpjack-1",
        },
      },
    },
    {
      type = "technology",
      name = "bob-pumpjacks-2",
      icon = "__base__/graphics/technology/oil-gathering.png",
      icon_size = 256,
      icon_mipmaps = 4,
      order = "d-a-c-2",
      prerequisites = {
        "bob-pumpjacks-1",
        "advanced-electronics",
      },
      unit = {
        count = 75,
        time = 30,
        ingredients = {
          { "automation-science-pack", 1 },
          { "logistic-science-pack", 2 },
        },
      },
      effects = {
        {
          type = "unlock-recipe",
          recipe = "bob-pumpjack-2",
        },
      },
    },
    {
      type = "technology",
      name = "bob-pumpjacks-3",
      icon = "__base__/graphics/technology/oil-gathering.png",
      icon_size = 256,
      icon_mipmaps = 4,
      order = "d-a-c-3",
      prerequisites = {
        "bob-pumpjacks-2",
        "advanced-electronics-2",
      },
      unit = {
        count = 100,
        time = 30,
        ingredients = {
          { "automation-science-pack", 1 },
          { "logistic-science-pack", 1 },
          { "chemical-science-pack", 1 },
        },
      },
      effects = {
        {
          type = "unlock-recipe",
          recipe = "bob-pumpjack-3",
        },
      },
    },
    {
      type = "technology",
      name = "bob-pumpjacks-4",
      icon = "__base__/graphics/technology/oil-gathering.png",
      icon_size = 256,
      icon_mipmaps = 4,
      order = "d-a-c-4",
      prerequisites = {
        "bob-pumpjacks-3",
      },
      unit = {
        count = 150,
        time = 30,
        ingredients = {
          { "automation-science-pack", 1 },
          { "logistic-science-pack", 1 },
          { "chemical-science-pack", 1 },
          { "production-science-pack", 1 },
        },
      },
      effects = {
        {
          type = "unlock-recipe",
          recipe = "bob-pumpjack-4",
        },
      },
    },
  })
end
