data:extend({
  {
    type = "recipe",
    name = "bob-ruby-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "ruby-ore", amount = 1 },
    },
    results = { { type = "item", name = "ruby-3", amount = 4 } },
  },
  {
    type = "recipe",
    name = "bob-sapphire-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "sapphire-ore", amount = 1 },
    },
    results = { { type = "item", name = "sapphire-3", amount = 4 } },
  },
  {
    type = "recipe",
    name = "bob-emerald-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "emerald-ore", amount = 1 },
    },
    results = { { type = "item", name = "emerald-3", amount = 4 } },
  },
  {
    type = "recipe",
    name = "bob-amethyst-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "amethyst-ore", amount = 1 },
    },
    results = { { type = "item", name = "amethyst-3", amount = 4 } },
  },
  {
    type = "recipe",
    name = "bob-topaz-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "topaz-ore", amount = 1 },
    },
    results = { { type = "item", name = "topaz-3", amount = 4 } },
  },
  {
    type = "recipe",
    name = "bob-diamond-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "diamond-ore", amount = 1 },
    },
    results = { { type = "item", name = "diamond-3", amount = 4 } },
  },

  {
    type = "recipe",
    name = "bob-ruby-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "ruby-3", amount = 1 },
      { type = "item", name = "grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "ruby-4", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-sapphire-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "sapphire-3", amount = 1 },
      { type = "item", name = "grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "sapphire-4", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-emerald-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "emerald-3", amount = 1 },
      { type = "item", name = "grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "emerald-4", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-amethyst-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "amethyst-3", amount = 1 },
      { type = "item", name = "grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "amethyst-4", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-topaz-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "topaz-3", amount = 1 },
      { type = "item", name = "grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "topaz-4", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-diamond-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "diamond-3", amount = 1 },
      { type = "item", name = "grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "diamond-4", amount = 1 } },
  },

  {
    type = "recipe",
    name = "bob-ruby-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "ruby-4", amount = 1 },
      { type = "item", name = "polishing-wheel", amount = 1 },
      { type = "item", name = "polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "ruby-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-sapphire-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "sapphire-4", amount = 1 },
      { type = "item", name = "polishing-wheel", amount = 1 },
      { type = "item", name = "polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "sapphire-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-emerald-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "emerald-4", amount = 1 },
      { type = "item", name = "polishing-wheel", amount = 1 },
      { type = "item", name = "polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "emerald-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-amethyst-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "amethyst-4", amount = 1 },
      { type = "item", name = "polishing-wheel", amount = 1 },
      { type = "item", name = "polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "amethyst-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-topaz-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "topaz-4", amount = 1 },
      { type = "item", name = "polishing-wheel", amount = 1 },
      { type = "item", name = "polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "topaz-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-diamond-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "diamond-4", amount = 1 },
      { type = "item", name = "polishing-wheel", amount = 1 },
      { type = "item", name = "polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "diamond-5", amount = 1 } },
  },
})
