data:extend({
  {
    type = "recipe",
    name = "bob-ruby-3",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bob-ruby-ore", amount = 1 },
    },
    results = { { type = "item", name = "bob-ruby-3", amount = 4 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-sapphire-3",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bob-sapphire-ore", amount = 1 },
    },
    results = { { type = "item", name = "bob-sapphire-3", amount = 4 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-emerald-3",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bob-emerald-ore", amount = 1 },
    },
    results = { { type = "item", name = "bob-emerald-3", amount = 4 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-amethyst-3",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bob-amethyst-ore", amount = 1 },
    },
    results = { { type = "item", name = "bob-amethyst-3", amount = 4 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-topaz-3",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bob-topaz-ore", amount = 1 },
    },
    results = { { type = "item", name = "bob-topaz-3", amount = 4 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-diamond-3",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bob-diamond-ore", amount = 1 },
    },
    results = { { type = "item", name = "bob-diamond-3", amount = 4 } },
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-ruby-4",
    category = "crafting-with-fluid",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "bob-ruby-3", amount = 1 },
      { type = "item", name = "bob-grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "bob-ruby-4", amount = 1 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-sapphire-4",
    category = "crafting-with-fluid",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "bob-sapphire-3", amount = 1 },
      { type = "item", name = "bob-grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "bob-sapphire-4", amount = 1 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-emerald-4",
    category = "crafting-with-fluid",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "bob-emerald-3", amount = 1 },
      { type = "item", name = "bob-grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "bob-emerald-4", amount = 1 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-amethyst-4",
    category = "crafting-with-fluid",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "bob-amethyst-3", amount = 1 },
      { type = "item", name = "bob-grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "bob-amethyst-4", amount = 1 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-topaz-4",
    category = "crafting-with-fluid",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "bob-topaz-3", amount = 1 },
      { type = "item", name = "bob-grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "bob-topaz-4", amount = 1 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "bob-diamond-4",
    category = "crafting-with-fluid",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.5,
    ingredients = {
      { type = "item", name = "bob-diamond-3", amount = 1 },
      { type = "item", name = "bob-grinding-wheel", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = { { type = "item", name = "bob-diamond-4", amount = 1 } },
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-ruby-5",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "bob-ruby-4", amount = 1 },
      { type = "item", name = "bob-polishing-wheel", amount = 1 },
      { type = "item", name = "bob-polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "bob-ruby-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-sapphire-5",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "bob-sapphire-4", amount = 1 },
      { type = "item", name = "bob-polishing-wheel", amount = 1 },
      { type = "item", name = "bob-polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "bob-sapphire-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-emerald-5",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "bob-emerald-4", amount = 1 },
      { type = "item", name = "bob-polishing-wheel", amount = 1 },
      { type = "item", name = "bob-polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "bob-emerald-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-amethyst-5",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "bob-amethyst-4", amount = 1 },
      { type = "item", name = "bob-polishing-wheel", amount = 1 },
      { type = "item", name = "bob-polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "bob-amethyst-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-topaz-5",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "bob-topaz-4", amount = 1 },
      { type = "item", name = "bob-polishing-wheel", amount = 1 },
      { type = "item", name = "bob-polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "bob-topaz-5", amount = 1 } },
  },
  {
    type = "recipe",
    name = "bob-diamond-5",
    category = "advanced-crafting",
    enabled = false,
    auto_recycle = false,
    energy_required = 17.5,
    ingredients = {
      { type = "item", name = "bob-diamond-4", amount = 1 },
      { type = "item", name = "bob-polishing-wheel", amount = 1 },
      { type = "item", name = "bob-polishing-compound", amount = 1 },
    },
    results = { { type = "item", name = "bob-diamond-5", amount = 1 } },
  },
})
