data:extend({
  {
    type = "recipe",
    name = "bob-ruby-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { "ruby-ore", 1 },
    },
    results = {{ type = "item", name = "ruby-3", amount = 4 }},
  },
  {
    type = "recipe",
    name = "bob-sapphire-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { "sapphire-ore", 1 },
    },
    results = {{ type = "item", name = "sapphire-3", amount = 4 }},
  },
  {
    type = "recipe",
    name = "bob-emerald-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { "emerald-ore", 1 },
    },
    results = {{ type = "item", name = "emerald-3", amount = 4 }},
  },
  {
    type = "recipe",
    name = "bob-amethyst-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { "amethyst-ore", 1 },
    },
    results = {{ type = "item", name = "amethyst-3", amount = 4 }},
  },
  {
    type = "recipe",
    name = "bob-topaz-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { "topaz-ore", 1 },
    },
    results = {{ type = "item", name = "topaz-3", amount = 4 }},
  },
  {
    type = "recipe",
    name = "bob-diamond-3",
    category = "crafting-machine",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { "diamond-ore", 1 },
    },
    results = {{ type = "item", name = "diamond-3", amount = 4 }},
  },

  {
    type = "recipe",
    name = "bob-ruby-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { "ruby-3", 1 },
      { "grinding-wheel", 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {{ type = "item", name = "ruby-4", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-sapphire-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { "sapphire-3", 1 },
      { "grinding-wheel", 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {{ type = "item", name = "sapphire-4", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-emerald-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { "emerald-3", 1 },
      { "grinding-wheel", 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {{ type = "item", name = "emerald-4", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-amethyst-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { "amethyst-3", 1 },
      { "grinding-wheel", 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {{ type = "item", name = "amethyst-4", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-topaz-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { "topaz-3", 1 },
      { "grinding-wheel", 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {{ type = "item", name = "topaz-4", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-diamond-4",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 3.5,
    ingredients = {
      { "diamond-3", 1 },
      { "grinding-wheel", 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {{ type = "item", name = "diamond-4", amount = 1 }},
  },

  {
    type = "recipe",
    name = "bob-ruby-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { "ruby-4", 1 },
      { "polishing-wheel", 1 },
      { "polishing-compound", 1 },
    },
    results = {{ type = "item", name = "ruby-5", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-sapphire-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { "sapphire-4", 1 },
      { "polishing-wheel", 1 },
      { "polishing-compound", 1 },
    },
    results = {{ type = "item", name = "sapphire-5", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-emerald-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { "emerald-4", 1 },
      { "polishing-wheel", 1 },
      { "polishing-compound", 1 },
    },
    results = {{ type = "item", name = "emerald-5", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-amethyst-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { "amethyst-4", 1 },
      { "polishing-wheel", 1 },
      { "polishing-compound", 1 },
    },
    results = {{ type = "item", name = "amethyst-5", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-topaz-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { "topaz-4", 1 },
      { "polishing-wheel", 1 },
      { "polishing-compound", 1 },
    },
    results = {{ type = "item", name = "topaz-5", amount = 1 }},
  },
  {
    type = "recipe",
    name = "bob-diamond-5",
    category = "crafting-machine",
    enabled = false,
    energy_required = 17.5,
    ingredients = {
      { "diamond-4", 1 },
      { "polishing-wheel", 1 },
      { "polishing-compound", 1 },
    },
    results = {{ type = "item", name = "diamond-5", amount = 1 }},
  },
})
