data:extend({
  {
    type = "recipe",
    name = "bob-lead-plate",
    category = "smelting",
    subgroup = "bob-material-smelting",
    energy_required = 3.2,
    emissions_multiplier = 10,
    ingredients = { { type = "item", name = "lead-ore", amount = 1 } },
    results = { { type = "item", name = "bob-lead-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "silver-plate",
    category = "smelting",
    subgroup = "bob-material-smelting",
    energy_required = 3.2,
    ingredients = { { type = "item", name = "silver-ore", amount = 1 } },
    results = { { type = "item", name = "silver-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-tin-plate",
    category = "smelting",
    subgroup = "bob-material-smelting",
    energy_required = 3.2,
    ingredients = { { type = "item", name = "tin-ore", amount = 1 } },
    results = { { type = "item", name = "bob-tin-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-lead-plate-2",
    category = "chemical-furnace",
    subgroup = "bob-material-chemical",
    energy_required = 6.4,
    enabled = false,
    ingredients = {
      { type = "item", name = "lead-oxide", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
    },
    results = { { type = "item", name = "bob-lead-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-gold-plate",
    category = "chemical-furnace",
    subgroup = "bob-material-chemical",
    energy_required = 3.2,
    enabled = false,
    ingredients = {
      { type = "item", name = "gold-ore", amount = 1 },
      { type = "fluid", name = "chlorine", amount = 3 },
    },
    results = { { type = "item", name = "bob-gold-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "cobalt-plate",
    category = "chemical-furnace",
    subgroup = "bob-material-chemical",
    energy_required = 3.2,
    enabled = false,
    ingredients = {
      { type = "item", name = "cobalt-oxide", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = { { type = "item", name = "cobalt-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-tungsten-plate",
    enabled = false,
    category = "mixing-furnace",
    subgroup = "bob-alloy",
    energy_required = 16,
    ingredients = {
      { type = "item", name = "bob-nickel-plate", amount = 1 },
      { type = "item", name = "powdered-tungsten", amount = 4 },
    },
    results = { { type = "item", name = "bob-tungsten-plate", amount = 5 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-zinc-plate",
    category = "electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 3.2,
    enabled = false,
    ingredients = {
      { type = "item", name = "zinc-ore", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = { { type = "item", name = "bob-zinc-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-nickel-plate",
    icon = "__bobplates__/graphics/icons/plate/nickel-plate.png",
    icon_size = 64,
    subgroup = "bob-material-electrolysis",
    order = "c-a-f[nickel-plate]",
    category = "electrolysis",
    enabled = false,
    energy_required = 3.2,
    ingredients = {
      { type = "item", name = "nickel-ore", amount = 1 },
      { type = "fluid", name = "oxygen", amount = 8 },
    },
    results = {
      { type = "fluid", name = "sulfur-dioxide", amount = 10 },
      { type = "item", name = "bob-nickel-plate", amount = 1 },
    },
    main_product = "bob-nickel-plate",
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-aluminium-plate",
    category = "electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 6.4,
    enabled = false,
    ingredients = {
      { type = "item", name = "alumina", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
    },
    results = { { type = "item", name = "bob-aluminium-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-titanium-plate",
    category = "electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 6.4,
    enabled = false,
    ingredients = {
      { type = "item", name = "calcium-chloride", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
      { type = "item", name = "rutile-ore", amount = 2 },
    },
    results = { { type = "item", name = "bob-titanium-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-silicon-plate",
    category = "electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 6.4,
    enabled = false,
    ingredients = {
      { type = "item", name = "calcium-chloride", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
      { type = "item", name = "quartz", amount = 2 },
    },
    results = { { type = "item", name = "bob-silicon-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-lithium",
    category = "electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 3.2,
    enabled = false,
    ingredients = {
      { type = "item", name = "lithium-chloride", amount = 1 },
    },
    results = { { type = "item", name = "bob-lithium", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },
})
