data:extend({
  {
    type = "recipe",
    name = "bob-lead-plate",
    category = "smelting",
    subgroup = "bob-material-smelting",
    energy_required = 3.2,
    emissions_multiplier = 10,
    auto_recycle = false,
    ingredients = { { type = "item", name = "bob-lead-ore", amount = 1 } },
    results = { { type = "item", name = "bob-lead-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-silver-plate",
    category = "smelting",
    subgroup = "bob-material-smelting",
    energy_required = 3.2,
    auto_recycle = false,
    ingredients = { { type = "item", name = "bob-silver-ore", amount = 1 } },
    results = { { type = "item", name = "bob-silver-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-tin-plate",
    category = "smelting",
    subgroup = "bob-material-smelting",
    energy_required = 3.2,
    auto_recycle = false,
    ingredients = { { type = "item", name = "bob-tin-ore", amount = 1 } },
    results = { { type = "item", name = "bob-tin-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-lead-plate-2",
    category = "bob-chemical-furnace",
    subgroup = "bob-material-chemical",
    energy_required = 6.4,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-lead-oxide", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
    },
    results = { { type = "item", name = "bob-lead-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-gold-plate",
    category = "bob-chemical-furnace",
    subgroup = "bob-material-chemical",
    energy_required = 3.2,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-gold-ore", amount = 1 },
      { type = "fluid", name = "bob-chlorine", amount = 3 },
    },
    results = { { type = "item", name = "bob-gold-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-cobalt-plate",
    category = "bob-chemical-furnace",
    subgroup = "bob-material-chemical",
    energy_required = 3.2,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-cobalt-oxide", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = { { type = "item", name = "bob-cobalt-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-tungsten-plate",
    enabled = false,
    auto_recycle = false,
    category = "bob-mixing-furnace",
    subgroup = "bob-alloy",
    energy_required = 16,
    ingredients = {
      { type = "item", name = "bob-nickel-plate", amount = 1 },
      { type = "item", name = "bob-powdered-tungsten", amount = 4 },
    },
    results = { { type = "item", name = "bob-tungsten-plate", amount = 5 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-zinc-plate",
    category = "bob-electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 3.2,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-zinc-ore", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = { { type = "item", name = "bob-zinc-plate", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-nickel-plate",
    icon = "__bobplates__/graphics/icons/plate/nickel-plate.png",
    icon_size = 64,
    subgroup = "bob-material-electrolysis",
    order = "c-a-f[nickel-plate]",
    category = "bob-electrolysis",
    enabled = false,
    auto_recycle = false,
    energy_required = 3.2,
    ingredients = {
      { type = "item", name = "bob-nickel-ore", amount = 1 },
      { type = "fluid", name = "bob-oxygen", amount = 8 },
    },
    results = {
      { type = "fluid", name = "bob-sulfur-dioxide", amount = 10 },
      { type = "item", name = "bob-nickel-plate", amount = 1 },
    },
    main_product = "bob-nickel-plate",
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-aluminium-plate",
    category = "bob-electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 6.4,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-alumina", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
    },
    results = { { type = "item", name = "bob-aluminium-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-titanium-plate",
    category = "bob-electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 6.4,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-calcium-chloride", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
      { type = "item", name = "bob-rutile-ore", amount = 2 },
    },
    results = { { type = "item", name = "bob-titanium-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-silicon-plate",
    category = "bob-electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 6.4,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-calcium-chloride", amount = 2 },
      { type = "item", name = "bob-carbon", amount = 1 },
      { type = "item", name = "bob-quartz", amount = 2 },
    },
    results = { { type = "item", name = "bob-silicon-plate", amount = 2 } },
    allow_decomposition = false,
    allow_productivity = true,
  },

  {
    type = "recipe",
    name = "bob-lithium",
    category = "bob-electrolysis",
    subgroup = "bob-material-electrolysis",
    energy_required = 3.2,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "bob-lithium-chloride", amount = 1 },
    },
    results = { { type = "item", name = "bob-lithium", amount = 1 } },
    allow_decomposition = false,
    allow_productivity = true,
  },
})
