if bobmods.modules.ModulesLab then
  data.raw["lab"]["lab"].fast_replaceable_group = "lab"

  data:extend({
    {
      type = "item",
      name = "lab-module",
      icon = "__base__/graphics/icons/lab.png",
      icon_size = 64,
      subgroup = "production-machine",
      order = "g[lab]-a[module]",
      place_result = "lab-module",
      stack_size = 10,
    },

    {
      type = "lab",
      name = "lab-module",
      icon = "__base__/graphics/icons/lab.png",
      icon_size = 64,
      flags = { "placeable-player", "player-creation" },
      minable = { mining_time = 1, result = "lab-module" },
      max_health = 200,
      corpse = "big-remnants",
      collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
      selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
      light = { intensity = 0.75, size = 8 },
      on_animation = {
        layers = {
          {
            filename = "__base__/graphics/entity/lab/lab.png",
            width = 98,
            height = 87,
            frame_count = 33,
            line_length = 11,
            animation_speed = 1 / 3,
            shift = util.by_pixel(0, 1.5),
            hr_version = {
              filename = "__base__/graphics/entity/lab/hr-lab.png",
              width = 194,
              height = 174,
              frame_count = 33,
              line_length = 11,
              animation_speed = 1 / 3,
              shift = util.by_pixel(0, 1.5),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/lab/lab-integration.png",
            width = 122,
            height = 81,
            frame_count = 1,
            line_length = 1,
            repeat_count = 33,
            animation_speed = 1 / 3,
            shift = util.by_pixel(0, 15.5),
            hr_version = {
              filename = "__base__/graphics/entity/lab/hr-lab-integration.png",
              width = 242,
              height = 162,
              frame_count = 1,
              line_length = 1,
              repeat_count = 33,
              animation_speed = 1 / 3,
              shift = util.by_pixel(0, 15.5),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/lab/lab-shadow.png",
            width = 122,
            height = 68,
            frame_count = 1,
            line_length = 1,
            repeat_count = 33,
            animation_speed = 1 / 3,
            shift = util.by_pixel(13, 11),
            draw_as_shadow = true,
            hr_version = {
              filename = "__base__/graphics/entity/lab/hr-lab-shadow.png",
              width = 242,
              height = 136,
              frame_count = 1,
              line_length = 1,
              repeat_count = 33,
              animation_speed = 1 / 3,
              shift = util.by_pixel(13, 11),
              scale = 0.5,
              draw_as_shadow = true,
            },
          },
        },
      },
      off_animation = {
        layers = {
          {
            filename = "__base__/graphics/entity/lab/lab.png",
            width = 98,
            height = 87,
            frame_count = 1,
            shift = util.by_pixel(0, 1.5),
            hr_version = {
              filename = "__base__/graphics/entity/lab/hr-lab.png",
              width = 194,
              height = 174,
              frame_count = 1,
              shift = util.by_pixel(0, 1.5),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/lab/lab-integration.png",
            width = 122,
            height = 81,
            frame_count = 1,
            shift = util.by_pixel(0, 15.5),
            hr_version = {
              filename = "__base__/graphics/entity/lab/hr-lab-integration.png",
              width = 242,
              height = 162,
              frame_count = 1,
              shift = util.by_pixel(0, 15.5),
              scale = 0.5,
            },
          },
          {
            filename = "__base__/graphics/entity/lab/lab-shadow.png",
            width = 122,
            height = 68,
            frame_count = 1,
            shift = util.by_pixel(13, 11),
            draw_as_shadow = true,
            hr_version = {
              filename = "__base__/graphics/entity/lab/hr-lab-shadow.png",
              width = 242,
              height = 136,
              frame_count = 1,
              shift = util.by_pixel(13, 11),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
      },
      energy_source = {
        type = "electric",
        usage_priority = "secondary-input",
      },
      working_sound = {
        sound = {
          filename = "__base__/sound/lab.ogg",
          volume = 0.7,
        },
        apparent_volume = 1.5,
      },
      energy_usage = "75kW",
      inputs = {
        "module-case",
        "module-circuit-board",
        "speed-processor",
        "effectivity-processor",
        "productivity-processor",
        "pollution-clean-processor",
        "pollution-create-processor",
      },
      researching_speed = 1.5,
      module_specification = {
        module_slots = 3,
        module_info_icon_shift = { 0, 0.5 },
        module_info_multi_row_initial_height_modifier = -0.3,
      },
      fast_replaceable_group = "lab",
    },

    {
      type = "recipe",
      name = "lab-module",
      enabled = false,
      energy_required = 15,
      ingredients = {
        { type = "item", name = "lab", amount = 1 },
        { type = "item", name = "speed-processor", amount = 5 },
        { type = "item", name = "effectivity-processor", amount = 5 },
        { type = "item", name = "productivity-processor", amount = 5 },
      },
      results = { { type = "item", name = "lab-module", amount = 1 } },
    },
  })

  bobmods.lib.tech.add_recipe_unlock("modules", "lab-module")
  if DiscoScience and DiscoScience.prepareLab then
    DiscoScience.prepareLab(data.raw["lab"]["lab-module"])
  end
end
