data:extend({
  {
    type = "bool-setting",
    name = "bobmods-ores-infiniteore",
    setting_type = "startup",
    default_value = false,
  },

  {
    type = "bool-setting",
    name = "bobmods-ores-unsortedgemore",
    setting_type = "startup",
    default_value = false,
  },

  {
    type = "bool-setting",
    name = "bobmods-ores-leadgivesnickel",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "double-setting",
    name = "bobmods-ores-leadnickelratio",
    setting_type = "startup",
    default_value = 0.6,
    maximum_value = 1,
    minimum_value = 0,
  },

  {
    type = "bool-setting",
    name = "bobmods-ores-nickelgivescobalt",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "double-setting",
    name = "bobmods-ores-nickelcobaltratio",
    setting_type = "startup",
    default_value = 0.4,
    maximum_value = 1,
    minimum_value = 0,
  },

  {
    type = "bool-setting",
    name = "bobmods-ores-gemsfromotherores",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "double-setting",
    name = "bobmods-ores-gemprobability",
    setting_type = "startup",
    default_value = 0.05,
    maximum_value = 1,
    minimum_value = 0,
  },

  {
    type = "double-setting",
    name = "bobmods-gems-rubyratio",
    setting_type = "startup",
    default_value = 1,
    maximum_value = 1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "bobmods-gems-sapphireratio",
    setting_type = "startup",
    default_value = 0.8,
    maximum_value = 1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "bobmods-gems-emeraldratio",
    setting_type = "startup",
    default_value = 0.6,
    maximum_value = 1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "bobmods-gems-amethystratio",
    setting_type = "startup",
    default_value = 0.5,
    maximum_value = 1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "bobmods-gems-topazratio",
    setting_type = "startup",
    default_value = 0.4,
    maximum_value = 1,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "bobmods-gems-diamondratio",
    setting_type = "startup",
    default_value = 0.2,
    maximum_value = 1,
    minimum_value = 0,
  },

  {
    type = "bool-setting",
    name = "bobmods-ores-enablebauxite",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablecobaltore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablegemsore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablegoldore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enableleadore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablenickelore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablequartz",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablerutile",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablesilverore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablesulfur",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enabletinore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enabletungstenore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablezincore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablewaterores",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-enablethoriumore",
    setting_type = "startup",
    default_value = false,
  },
  {
    type = "bool-setting",
    name = "bobmods-ores-startinggroundwater",
    setting_type = "startup",
    default_value = false,
  },
})
